//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquationElements {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ElementsExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ElementsExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EquationElements.ElementsExceptionMessages", typeof(ElementsExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is not valid..
        /// </summary>
        public static string FactorialWasNotAnIntegerAfterParameter {
            get {
                return ResourceManager.GetString("FactorialWasNotAnIntegerAfterParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factorials must be integers of 1 or more. .
        /// </summary>
        public static string FactorialWasNotAnIntegerBeforeParameter {
            get {
                return ResourceManager.GetString("FactorialWasNotAnIntegerBeforeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factorials must be integers of 1 or more..
        /// </summary>
        public static string FactorialWasNotAnIntegerDefault {
            get {
                return ResourceManager.GetString("FactorialWasNotAnIntegerDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name..
        /// </summary>
        public static string NameOfWordIsNullOrEmpty {
            get {
                return ResourceManager.GetString("NameOfWordIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot be the same as an Operator or Function..
        /// </summary>
        public static string NameWasSameAsOperatorOrFunction {
            get {
                return ResourceManager.GetString("NameWasSameAsOperatorOrFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to compare a Number to a non-Number..
        /// </summary>
        public static string NumberCompareFail {
            get {
                return ResourceManager.GetString("NumberCompareFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried to create a number is that was too large, small, or not Real..
        /// </summary>
        public static string OverloadedNumberDefault {
            get {
                return ResourceManager.GetString("OverloadedNumberDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is not valid..
        /// </summary>
        public static string RandomWasNotAnIntegerAfterParameter {
            get {
                return ResourceManager.GetString("RandomWasNotAnIntegerAfterParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers used in Random must be integers. .
        /// </summary>
        public static string RandomWasNotAnIntegerBeforeParameter {
            get {
                return ResourceManager.GetString("RandomWasNotAnIntegerBeforeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers used in Random must be integers..
        /// </summary>
        public static string RandomWasNotAnIntegerDefault {
            get {
                return ResourceManager.GetString("RandomWasNotAnIntegerDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is empty or contains only spaces..
        /// </summary>
        public static string StringIsNullEmptyOrOnlySpacesAfterParameter {
            get {
                return ResourceManager.GetString("StringIsNullEmptyOrOnlySpacesAfterParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  could not be turned into a number..
        /// </summary>
        public static string StringWasNotANumberAfterParameter {
            get {
                return ResourceManager.GetString("StringWasNotANumberAfterParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StringWasNotANumberBeforeParameter {
            get {
                return ResourceManager.GetString("StringWasNotANumberBeforeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried to turn something unidentifiable into a number..
        /// </summary>
        public static string StringWasNotANumberDefault {
            get {
                return ResourceManager.GetString("StringWasNotANumberDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to compare a Word to a non-Word.
        /// </summary>
        public static string WordCompareFail {
            get {
                return ResourceManager.GetString("WordCompareFail", resourceCulture);
            }
        }
    }
}
