//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquationElements {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FunctionRepresentations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FunctionRepresentations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EquationElements.FunctionRepresentations", typeof(FunctionRepresentations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abs.
        /// </summary>
        public static string AbsoluteShortWord {
            get {
                return ResourceManager.GetString("AbsoluteShortWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to absolute.
        /// </summary>
        public static string AbsoluteWord {
            get {
                return ResourceManager.GetString("AbsoluteWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acos.
        /// </summary>
        public static string ACosWord {
            get {
                return ResourceManager.GetString("ACosWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asin.
        /// </summary>
        public static string ASinWord {
            get {
                return ResourceManager.GetString("ASinWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to atan.
        /// </summary>
        public static string ATanWord {
            get {
                return ResourceManager.GetString("ATanWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ceil.
        /// </summary>
        public static string CeilingShortWord {
            get {
                return ResourceManager.GetString("CeilingShortWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ceiling.
        /// </summary>
        public static string CeilingWord {
            get {
                return ResourceManager.GetString("CeilingWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cosh.
        /// </summary>
        public static string CoshWord {
            get {
                return ResourceManager.GetString("CoshWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cos.
        /// </summary>
        public static string CosWord {
            get {
                return ResourceManager.GetString("CosWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to evenround.
        /// </summary>
        public static string EvenRoundWord {
            get {
                return ResourceManager.GetString("EvenRoundWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !.
        /// </summary>
        public static string FactorialSymbol {
            get {
                return ResourceManager.GetString("FactorialSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to factorial.
        /// </summary>
        public static string FactorialWord {
            get {
                return ResourceManager.GetString("FactorialWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to floor.
        /// </summary>
        public static string FloorWord {
            get {
                return ResourceManager.GetString("FloorWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log.
        /// </summary>
        public static string LogWord {
            get {
                return ResourceManager.GetString("LogWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ln.
        /// </summary>
        public static string NaturalLogShortWord {
            get {
                return ResourceManager.GetString("NaturalLogShortWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rand.
        /// </summary>
        public static string RandomShortWord {
            get {
                return ResourceManager.GetString("RandomShortWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to random.
        /// </summary>
        public static string RandomWord {
            get {
                return ResourceManager.GetString("RandomWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to round.
        /// </summary>
        public static string RoundWord {
            get {
                return ResourceManager.GetString("RoundWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sinh.
        /// </summary>
        public static string SinhWord {
            get {
                return ResourceManager.GetString("SinhWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sin.
        /// </summary>
        public static string SinWord {
            get {
                return ResourceManager.GetString("SinWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tanh.
        /// </summary>
        public static string TanhWord {
            get {
                return ResourceManager.GetString("TanhWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tan.
        /// </summary>
        public static string TanWord {
            get {
                return ResourceManager.GetString("TanWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trunc.
        /// </summary>
        public static string TruncateShortWord {
            get {
                return ResourceManager.GetString("TruncateShortWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to truncate.
        /// </summary>
        public static string TruncateWord {
            get {
                return ResourceManager.GetString("TruncateWord", resourceCulture);
            }
        }
    }
}
