//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquationElements {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OperatorRepresentations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OperatorRepresentations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EquationElements.OperatorRepresentations", typeof(OperatorRepresentations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string AdditionSymbol {
            get {
                return ResourceManager.GetString("AdditionSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        public static string ArgumentSeperatorSymbol {
            get {
                return ResourceManager.GetString("ArgumentSeperatorSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        public static string ComputerDivisionSymbol {
            get {
                return ResourceManager.GetString("ComputerDivisionSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string ComputerMultiplicationSymbol {
            get {
                return ResourceManager.GetString("ComputerMultiplicationSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        public static string CurlyClosingBracketSymbol {
            get {
                return ResourceManager.GetString("CurlyClosingBracketSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {.
        /// </summary>
        public static string CurlyOpeningBracketSymbol {
            get {
                return ResourceManager.GetString("CurlyOpeningBracketSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⋅.
        /// </summary>
        public static string DotMultiplicationSymbol {
            get {
                return ResourceManager.GetString("DotMultiplicationSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        public static string EqualsSymbol {
            get {
                return ResourceManager.GetString("EqualsSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string ModulusSymbol {
            get {
                return ResourceManager.GetString("ModulusSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mod.
        /// </summary>
        public static string ModulusWord {
            get {
                return ResourceManager.GetString("ModulusWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÷.
        /// </summary>
        public static string PaperDivisionSymbol {
            get {
                return ResourceManager.GetString("PaperDivisionSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ×.
        /// </summary>
        public static string PaperMultiplicationSymbol {
            get {
                return ResourceManager.GetString("PaperMultiplicationSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        public static string ParenthesisClosingBracketSymbol {
            get {
                return ResourceManager.GetString("ParenthesisClosingBracketSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.
        /// </summary>
        public static string ParenthesisOpeningBracketSymbol {
            get {
                return ResourceManager.GetString("ParenthesisOpeningBracketSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^.
        /// </summary>
        public static string PowerSymbol {
            get {
                return ResourceManager.GetString("PowerSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to √.
        /// </summary>
        public static string RootSymbol {
            get {
                return ResourceManager.GetString("RootSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to root.
        /// </summary>
        public static string RootWord {
            get {
                return ResourceManager.GetString("RootWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ].
        /// </summary>
        public static string SquareClosingBracketSymbol {
            get {
                return ResourceManager.GetString("SquareClosingBracketSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [.
        /// </summary>
        public static string SquareOpeningBracketSymbol {
            get {
                return ResourceManager.GetString("SquareOpeningBracketSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string SubtractionSymbol {
            get {
                return ResourceManager.GetString("SubtractionSymbol", resourceCulture);
            }
        }
    }
}
