//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MehrozFractions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MehrozFractions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition Error..
        /// </summary>
        internal static string AdditionError {
            get {
                return ResourceManager.GetString("AdditionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert .
        /// </summary>
        internal static string CannotConvertBeforeParameter {
            get {
                return ResourceManager.GetString("CannotConvertBeforeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert to integer..
        /// </summary>
        internal static string CannotConvertToIntegerDefault {
            get {
                return ResourceManager.GetString("CannotConvertToIntegerDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert to 64-bit integer..
        /// </summary>
        internal static string CannotConvertToLongDefault {
            get {
                return ResourceManager.GetString("CannotConvertToLongDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string CompareToErrorAfterParameters {
            get {
                return ResourceManager.GetString("CompareToErrorAfterParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error comparing .
        /// </summary>
        internal static string CompareToErrorBeforeParameters {
            get {
                return ResourceManager.GetString("CompareToErrorBeforeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and .
        /// </summary>
        internal static string CompareToErrorBetweenParameters {
            get {
                return ResourceManager.GetString("CompareToErrorBetweenParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error comparing..
        /// </summary>
        internal static string CompareToErrorDefault {
            get {
                return ResourceManager.GetString("CompareToErrorDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gf {
            get {
                return ResourceManager.GetString("gf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulus Error..
        /// </summary>
        internal static string ModulusError {
            get {
                return ResourceManager.GetString("ModulusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication Error..
        /// </summary>
        internal static string MultiplicationError {
            get {
                return ResourceManager.GetString("MultiplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be convertible to a Fraction..
        /// </summary>
        internal static string MustBeConvertible {
            get {
                return ResourceManager.GetString("MustBeConvertible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is too large, too small, or cannot be represented..
        /// </summary>
        internal static string OverloadedNumberAfterParameter {
            get {
                return ResourceManager.GetString("OverloadedNumberAfterParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OverloadedNumberBeforeParameter {
            get {
                return ResourceManager.GetString("OverloadedNumberBeforeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number is too large, too small, or cannot be represented..
        /// </summary>
        internal static string OverloadedNumberDefault {
            get {
                return ResourceManager.GetString("OverloadedNumberDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        internal static string SeperatorSymbol {
            get {
                return ResourceManager.GetString("SeperatorSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SubtractionError {
            get {
                return ResourceManager.GetString("SubtractionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to integer..
        /// </summary>
        internal static string ToIntegerAfterParameter {
            get {
                return ResourceManager.GetString("ToIntegerAfterParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to 64-bit integer..
        /// </summary>
        internal static string ToLongAfterParameter {
            get {
                return ResourceManager.GetString("ToLongAfterParameter", resourceCulture);
            }
        }
    }
}
