//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DialogResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DialogResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calculations.DialogResources", typeof(DialogResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Add Constant.
        /// </summary>
        internal static string CannotAddConstantTitle {
            get {
                return ResourceManager.GetString("CannotAddConstantTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No answer to copy..
        /// </summary>
        internal static string CannotCopyAnswerMessage {
            get {
                return ResourceManager.GetString("CannotCopyAnswerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Copy.
        /// </summary>
        internal static string CannotCopyAnswerTitle {
            get {
                return ResourceManager.GetString("CannotCopyAnswerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Delete Constant.
        /// </summary>
        internal static string CannotDeleteConstantTitle {
            get {
                return ResourceManager.GetString("CannotDeleteConstantTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name can only contain letters, digits and spaces..
        /// </summary>
        internal static string ConstantNameInvalidCharacterMessage {
            get {
                return ResourceManager.GetString("ConstantNameInvalidCharacterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names with &quot;mod&quot;, &quot;root&quot; or &quot;E&quot;, next to digits, may cause the calculator to fail or give the wrong answer. Create Constant anyway?.
        /// </summary>
        internal static string ConstantNameNextToDigitsQuestion {
            get {
                return ResourceManager.GetString("ConstantNameNextToDigitsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Constant?.
        /// </summary>
        internal static string ConstantNameSurroundedByDigitsQuestionTitle {
            get {
                return ResourceManager.GetString("ConstantNameSurroundedByDigitsQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string DeleteConstantQuestionDialogMessageAfterParameter {
            get {
                return ResourceManager.GetString("DeleteConstantQuestionDialogMessageAfterParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete .
        /// </summary>
        internal static string DeleteConstantQuestionDialogMessageBeforeParameter {
            get {
                return ResourceManager.GetString("DeleteConstantQuestionDialogMessageBeforeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Constant?.
        /// </summary>
        internal static string DeleteConstantQuestionTitle {
            get {
                return ResourceManager.GetString("DeleteConstantQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export All Constants.
        /// </summary>
        internal static string ExportAllConstantsTitle {
            get {
                return ResourceManager.GetString("ExportAllConstantsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Search Results.
        /// </summary>
        internal static string ExportConstantsSearchResultsTitle {
            get {
                return ResourceManager.GetString("ExportConstantsSearchResultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export History.
        /// </summary>
        internal static string ExportHistoryTitle {
            get {
                return ResourceManager.GetString("ExportHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Constants.
        /// </summary>
        internal static string ImportConstantsTitle {
            get {
                return ResourceManager.GetString("ImportConstantsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import History.
        /// </summary>
        internal static string ImportHistoryTitle {
            get {
                return ResourceManager.GetString("ImportHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; already exists. Overwrite it?.
        /// </summary>
        internal static string OverwriteConstantQuestionAfterParameter {
            get {
                return ResourceManager.GetString("OverwriteConstantQuestionAfterParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.
        /// </summary>
        internal static string OverwriteConstantQuestionBeforeParameter {
            get {
                return ResourceManager.GetString("OverwriteConstantQuestionBeforeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite Constant?.
        /// </summary>
        internal static string OverwriteConstantQuestionTitle {
            get {
                return ResourceManager.GetString("OverwriteConstantQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pi and E cannot be deleted..
        /// </summary>
        internal static string PiAndECannotBeDeletedMessage {
            get {
                return ResourceManager.GetString("PiAndECannotBeDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pi and E cannot be modified..
        /// </summary>
        internal static string PiAndECannotBeModifiedMessage {
            get {
                return ResourceManager.GetString("PiAndECannotBeModifiedMessage", resourceCulture);
            }
        }
    }
}
