//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TooltipMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TooltipMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calculations.TooltipMessages", typeof(TooltipMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the number is negative, remove the negative sign..
        /// </summary>
        internal static string AbsoluteDescription {
            get {
                return ResourceManager.GetString("AbsoluteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: Absolute(Number).
        /// </summary>
        internal static string AbsoluteFormat {
            get {
                return ResourceManager.GetString("AbsoluteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: ACos(Number).
        /// </summary>
        internal static string ACosFormat {
            get {
                return ResourceManager.GetString("ACosFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; is also allowed.).
        /// </summary>
        internal static string AlsoAllowedAfterParameter {
            get {
                return ResourceManager.GetString("AlsoAllowedAfterParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&quot;.
        /// </summary>
        internal static string AlsoAllowedBeforeParameter {
            get {
                return ResourceManager.GetString("AlsoAllowedBeforeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: ASin(Number).
        /// </summary>
        internal static string ASinFormat {
            get {
                return ResourceManager.GetString("ASinFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: ATan(Number).
        /// </summary>
        internal static string ATanFormat {
            get {
                return ResourceManager.GetString("ATanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds up to the nearest integer..
        /// </summary>
        internal static string CeilingDescription {
            get {
                return ResourceManager.GetString("CeilingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: Ceiling(Number).
        /// </summary>
        internal static string CeilingFormat {
            get {
                return ResourceManager.GetString("CeilingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: Cos(Number).
        /// </summary>
        internal static string CosFormat {
            get {
                return ResourceManager.GetString("CosFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: Cosh(Number).
        /// </summary>
        internal static string CoshFormat {
            get {
                return ResourceManager.GetString("CoshFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divided by.
        /// </summary>
        internal static string DivideTooltip {
            get {
                return ResourceManager.GetString("DivideTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *10^ or Euler&apos;s number (2.718 to 3dp)..
        /// </summary>
        internal static string ETooltip {
            get {
                return ResourceManager.GetString("ETooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds to the nearest integer..
        /// </summary>
        internal static string EvenRoundDescription {
            get {
                return ResourceManager.GetString("EvenRoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: Even Round(Number).
        /// </summary>
        internal static string EvenRoundFormat {
            get {
                return ResourceManager.GetString("EvenRoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When .5, whichever is even..
        /// </summary>
        internal static string EvenRoundOnMidpoint {
            get {
                return ResourceManager.GetString("EvenRoundOnMidpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplies all the integers between.
        /// </summary>
        internal static string FactorialDescription {
            get {
                return ResourceManager.GetString("FactorialDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 and this integer together..
        /// </summary>
        internal static string FactorialDescriptionLine2 {
            get {
                return ResourceManager.GetString("FactorialDescriptionLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: Integer Factorial.
        /// </summary>
        internal static string FactorialFormat {
            get {
                return ResourceManager.GetString("FactorialFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds down to the nearest integer..
        /// </summary>
        internal static string FloorDescription {
            get {
                return ResourceManager.GetString("FloorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: Floor(Number).
        /// </summary>
        internal static string FloorFormat {
            get {
                return ResourceManager.GetString("FloorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert the selected answer into.
        /// </summary>
        internal static string InsertHistoryAnswerTooltip {
            get {
                return ResourceManager.GetString("InsertHistoryAnswerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the main calculation at the cursor..
        /// </summary>
        internal static string InsertHistoryAnswerTooltipLine2 {
            get {
                return ResourceManager.GetString("InsertHistoryAnswerTooltipLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert the selected calculation into the main.
        /// </summary>
        internal static string InsertHistoryCalculationTooltip {
            get {
                return ResourceManager.GetString("InsertHistoryCalculationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calculation at the cursor (surrounded by brackets)..
        /// </summary>
        internal static string InsertHistoryCalculationTooltipLine2 {
            get {
                return ResourceManager.GetString("InsertHistoryCalculationTooltipLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Log (Base E)..
        /// </summary>
        internal static string LnDescription {
            get {
                return ResourceManager.GetString("LnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: Ln(Number).
        /// </summary>
        internal static string LnFormat {
            get {
                return ResourceManager.GetString("LnFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: Log(Base , Number).
        /// </summary>
        internal static string LogFormat {
            get {
                return ResourceManager.GetString("LogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.g. Log(E, 10).
        /// </summary>
        internal static string LogFormatLine2 {
            get {
                return ResourceManager.GetString("LogFormatLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minus.
        /// </summary>
        internal static string MinusTooltip {
            get {
                return ResourceManager.GetString("MinusTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives the remainder after a division operation..
        /// </summary>
        internal static string ModDescription {
            get {
                return ResourceManager.GetString("ModDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: Number mod Number.
        /// </summary>
        internal static string ModFormat {
            get {
                return ResourceManager.GetString("ModFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus.
        /// </summary>
        internal static string PlusTooltip {
            get {
                return ResourceManager.GetString("PlusTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To the power of.
        /// </summary>
        internal static string PowerTooltip {
            get {
                return ResourceManager.GetString("PowerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates a random integer between.
        /// </summary>
        internal static string RandomDescription {
            get {
                return ResourceManager.GetString("RandomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two other, inclusive, integers..
        /// </summary>
        internal static string RandomDescriptionLine2 {
            get {
                return ResourceManager.GetString("RandomDescriptionLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: Random(min , max).
        /// </summary>
        internal static string RandomFormat {
            get {
                return ResourceManager.GetString("RandomFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        internal static string RootDescription {
            get {
                return ResourceManager.GetString("RootDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: Base √ Number.
        /// </summary>
        internal static string RootFormat {
            get {
                return ResourceManager.GetString("RootFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.g. 3√8 = 2.
        /// </summary>
        internal static string RootFormatLine2 {
            get {
                return ResourceManager.GetString("RootFormatLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds to the nearest integer..
        /// </summary>
        internal static string RoundDescription {
            get {
                return ResourceManager.GetString("RoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: Round(Number).
        /// </summary>
        internal static string RoundFormat {
            get {
                return ResourceManager.GetString("RoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When .5, up for positive numbers.
        /// </summary>
        internal static string RoundOnMidpoint {
            get {
                return ResourceManager.GetString("RoundOnMidpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and down for negative numbers..
        /// </summary>
        internal static string RoundOnMidpointLine2 {
            get {
                return ResourceManager.GetString("RoundOnMidpointLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: Sin(Number).
        /// </summary>
        internal static string SinFormat {
            get {
                return ResourceManager.GetString("SinFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: Sinh(Number).
        /// </summary>
        internal static string SinhFormat {
            get {
                return ResourceManager.GetString("SinhFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: Tan(Number).
        /// </summary>
        internal static string TanFormat {
            get {
                return ResourceManager.GetString("TanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: Tanh(Number).
        /// </summary>
        internal static string TanhFormat {
            get {
                return ResourceManager.GetString("TanhFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplied by.
        /// </summary>
        internal static string TimesTooltip {
            get {
                return ResourceManager.GetString("TimesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the decimal part of the number..
        /// </summary>
        internal static string TruncateDescription {
            get {
                return ResourceManager.GetString("TruncateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: Truncate(Number).
        /// </summary>
        internal static string TruncateFormat {
            get {
                return ResourceManager.GetString("TruncateFormat", resourceCulture);
            }
        }
    }
}
