//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TooltipMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TooltipMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calculations.TooltipMessages", typeof(TooltipMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the number is negative, remove the negative sign.
        ///Format: Absolute(Number).
        /// </summary>
        internal static string AbsoluteMain {
            get {
                return ResourceManager.GetString("AbsoluteMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: ACos(Number).
        /// </summary>
        internal static string ACos {
            get {
                return ResourceManager.GetString("ACos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; is also allowed.).
        /// </summary>
        internal static string AlsoAllowedAfterParameter {
            get {
                return ResourceManager.GetString("AlsoAllowedAfterParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&quot;.
        /// </summary>
        internal static string AlsoAllowedBeforeParameter {
            get {
                return ResourceManager.GetString("AlsoAllowedBeforeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: ASin(Number).
        /// </summary>
        internal static string ASin {
            get {
                return ResourceManager.GetString("ASin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: ATan(Number).
        /// </summary>
        internal static string ATan {
            get {
                return ResourceManager.GetString("ATan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds up to the nearest integer.
        ///Format: Ceiling(Number).
        /// </summary>
        internal static string Ceiling {
            get {
                return ResourceManager.GetString("Ceiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: Cos(Number).
        /// </summary>
        internal static string Cos {
            get {
                return ResourceManager.GetString("Cos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: Cosh(Number).
        /// </summary>
        internal static string Cosh {
            get {
                return ResourceManager.GetString("Cosh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divided by.
        /// </summary>
        internal static string Divide {
            get {
                return ResourceManager.GetString("Divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *10^ or Euler&apos;s number (2.718 to 3dp)..
        /// </summary>
        internal static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds to the nearest integer.
        ///(When .5, whichever is even.)
        ///Format: Even Round(Number).
        /// </summary>
        internal static string EvenRound {
            get {
                return ResourceManager.GetString("EvenRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplies all the integers between
        ///1 and this integer together.
        ///Format: Integer Factorial.
        /// </summary>
        internal static string FactorialMain {
            get {
                return ResourceManager.GetString("FactorialMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds down to the nearest integer.
        ///Format: Floor(Number).
        /// </summary>
        internal static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert the selected answer into
        ///the main calculation at the cursor..
        /// </summary>
        internal static string InsertHistoryAnswer {
            get {
                return ResourceManager.GetString("InsertHistoryAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert the selected calculation into the main
        ///calculation at the cursor (surrounded by brackets)..
        /// </summary>
        internal static string InsertHistoryCalculation {
            get {
                return ResourceManager.GetString("InsertHistoryCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Log (Base E).
        ///Format: Ln(Number).
        /// </summary>
        internal static string Ln {
            get {
                return ResourceManager.GetString("Ln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: Log(Base , Number)
        ///E.g. Log(E, 5).
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minus.
        /// </summary>
        internal static string Minus {
            get {
                return ResourceManager.GetString("Minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives the remainder after a division operation.
        ///Format: Number mod Number.
        /// </summary>
        internal static string ModMain {
            get {
                return ResourceManager.GetString("ModMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus.
        /// </summary>
        internal static string Plus {
            get {
                return ResourceManager.GetString("Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To the power of.
        /// </summary>
        internal static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates a random integer between
        ///two other, inclusive, integers.
        ///Format: Random(min , max).
        /// </summary>
        internal static string RandomMain {
            get {
                return ResourceManager.GetString("RandomMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root
        ///Format: Base √ Number
        ///E.g. 3√8 = 2.
        /// </summary>
        internal static string RootMain {
            get {
                return ResourceManager.GetString("RootMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds to the nearest integer.
        ///Format: Round(Number).
        /// </summary>
        internal static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: Sin(Number).
        /// </summary>
        internal static string Sin {
            get {
                return ResourceManager.GetString("Sin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: Sinh(Number).
        /// </summary>
        internal static string Sinh {
            get {
                return ResourceManager.GetString("Sinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: Tan(Number).
        /// </summary>
        internal static string Tan {
            get {
                return ResourceManager.GetString("Tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: Tanh(Number).
        /// </summary>
        internal static string Tanh {
            get {
                return ResourceManager.GetString("Tanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplied by.
        /// </summary>
        internal static string Times {
            get {
                return ResourceManager.GetString("Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the decimal part of the number.
        ///Format: Truncate(Number).
        /// </summary>
        internal static string Truncate {
            get {
                return ResourceManager.GetString("Truncate", resourceCulture);
            }
        }
    }
}
